services:
  db:
    image: postgres:15-alpine
    container_name: academy_quest_diamond 
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - quest_data:/var/lib/postgresql/data

volumes:
  quest_data: